/**
 * POLARSYNC Realistic Mock Datasets
 * Meets all SIH 2026 Problem Statement 26062 minimum requirements:
 * 10 Stations, 10 Expeditions, 30 Cargo, 40 Inventory, 30 Assets,
 * 40 Personnel, 10 Emergencies, 30 Tasks, 30 Notifications, 20 Audits, 20 Documents
 */

const stations = [
  { id: 'STN-01', name: 'Bharati Station', type: 'Permanent Research Station', lat: -69.4075, lng: 76.1908, region: 'Larsemann Hills, Antarctica', personnel: 35, assets: 42, inventoryHealth: 76, connectivity: 'Online', weather: '-22°C, Wind 28kt, Blizzard warning', estYear: 2012 },
  { id: 'STN-02', name: 'Maitri Station', type: 'Permanent Research Station', lat: -70.7667, lng: 11.7333, region: 'Schirmacher Oasis, Antarctica', personnel: 24, assets: 36, inventoryHealth: 84, connectivity: 'Online', weather: '-18°C, Wind 14kt, Clear', estYear: 1989 },
  { id: 'STN-03', name: 'Himadri Research Station', type: 'Arctic Research Base', lat: 78.9236, lng: 11.9286, region: 'Ny-Ålesund, Spitsbergen, Svalbard', personnel: 12, assets: 18, inventoryHealth: 92, connectivity: 'Online', weather: '-12°C, Wind 08kt, Polar Night', estYear: 2008 },
  { id: 'STN-04', name: 'IndARC Observatory', type: 'Sub-surface Moored Observatory', lat: 79.0022, lng: 11.9833, region: 'Kongsfjorden Fjord, Arctic Ocean', personnel: 2, assets: 6, inventoryHealth: 88, connectivity: 'Limited', weather: '-4°C water, Pack ice 45%', estYear: 2014 },
  { id: 'STN-05', name: 'Dakshin Gangotri Ice Depot', type: 'Fuel & Logistics Depot', lat: -70.0967, lng: 12.0000, region: 'Princess Astrid Coast, Antarctica', personnel: 0, assets: 8, inventoryHealth: 65, connectivity: 'Offline', weather: '-28°C, Wind 35kt, Drifting snow', estYear: 1983 },
  { id: 'STN-06', name: 'MV Vasiliy Golovnin', type: 'Expedition Vessel & Icebreaker', lat: -64.2000, lng: 48.5000, region: 'Southern Ocean Transit', personnel: 48, assets: 16, inventoryHealth: 95, connectivity: 'Limited', weather: '-6°C, Sea State 6, Swell 4.2m', estYear: 2002 },
  { id: 'STN-07', name: 'Cape Town Staging Base', type: 'Logistics & Supply Hub', lat: -33.9188, lng: 18.4233, region: 'Port of Cape Town, South Africa', personnel: 8, assets: 12, inventoryHealth: 98, connectivity: 'Online', weather: '+19°C, Wind 12kt, Sunny', estYear: 2005 },
  { id: 'STN-08', name: 'Novo Blue Ice Runway', type: 'Intercontinental Airfield', lat: -70.8167, lng: 11.7000, region: 'Queen Maud Land, Antarctica', personnel: 6, assets: 10, inventoryHealth: 72, connectivity: 'Limited', weather: '-24°C, Wind 22kt, Visibility 8km', estYear: 2001 },
  { id: 'STN-09', name: 'Larsemann Hills Camp Beta', type: 'Field Research Camp', lat: -69.4500, lng: 76.3500, region: 'Groenves Glacier Basin', personnel: 6, assets: 8, inventoryHealth: 58, connectivity: 'Limited', weather: '-26°C, Wind 31kt, Gusts 45kt', estYear: 2021 },
  { id: 'STN-10', name: 'Amery Ice Shelf Outpost', type: 'Glaciological Remote Station', lat: -70.2500, lng: 71.5000, region: 'Lambert Glacier Basin', personnel: 4, assets: 6, inventoryHealth: 60, connectivity: 'Offline', weather: '-32°C, Wind 40kt, Heavy drift', estYear: 2023 }
];

const expeditions = [
  { id: 'EXP-2026-01', name: '44th Indian Scientific Expedition to Antarctica (ISEA-44)', destination: 'Bharati Station & Maitri Station', station: 'Bharati Station', startDate: '2025-11-15', endDate: '2026-12-20', lead: 'Dr. Rajeshwar Sharma', personnelCount: 35, cargoCount: 18, status: 'Active', progress: 68, objectives: 'Long-term climate telemetry, ice-core retrieval, satellite calibration, and wintering survival operations.' },
  { id: 'EXP-2026-02', name: 'Arctic Winter Polar Night Survey 2026', destination: 'Himadri Research Station', station: 'Himadri Research Station', startDate: '2025-10-01', endDate: '2026-04-30', lead: 'Dr. Ananya Mukherjee', personnelCount: 12, cargoCount: 6, status: 'Active', progress: 82, objectives: 'Winter aerosol dynamics, Aurora borealis optical measurements, and upper atmosphere lidar profiling.' },
  { id: 'EXP-2026-03', name: 'Southern Ocean Biogeochemical Voyage', destination: 'MV Vasiliy Golovnin', station: 'MV Vasiliy Golovnin', startDate: '2026-01-10', endDate: '2026-05-15', lead: 'Dr. Vikramaditya Das', personnelCount: 22, cargoCount: 14, status: 'Active', progress: 45, objectives: 'Micro-plastic quantification, phytoplankton bloom mapping, and carbonate system saturation studies.' },
  { id: 'EXP-2026-04', name: 'Larsemann Hills Bedrock Deep Coring', destination: 'Larsemann Hills Camp Beta', station: 'Bharati Station', startDate: '2026-01-20', endDate: '2026-08-10', lead: 'Dr. Sunita Kulkarni', personnelCount: 18, cargoCount: 9, status: 'Active', progress: 54, objectives: 'Deep continental crust drilling and sub-glacial thermal gradient logging.' },
  { id: 'EXP-2026-05', name: 'Maitri Modernization & Hybrid Microgrid Phase II', destination: 'Maitri Station', station: 'Maitri Station', startDate: '2026-04-01', endDate: '2026-11-30', lead: 'Er. Tarun Verma', personnelCount: 15, cargoCount: 12, status: 'Planning', progress: 20, objectives: 'Installation of high-efficiency wind turbines, lithium-ion battery bank, and redundant diesel generator integration.' },
  { id: 'EXP-2026-06', name: 'Kongsfjorden Fjord Hydrographic Monitoring', destination: 'IndARC Observatory', station: 'Himadri Research Station', startDate: '2026-03-15', endDate: '2026-09-30', lead: 'Dr. Meera Nambiar', personnelCount: 8, cargoCount: 4, status: 'Approved', progress: 35, objectives: 'CTD mooring retrieval, Atlantic water inflow tracking, and glacial melt runoff characterization.' },
  { id: 'EXP-2026-07', name: 'Princess Astrid Coast UAV Glaciology Mapping', destination: 'Dakshin Gangotri Ice Depot', station: 'Maitri Station', startDate: '2026-05-01', endDate: '2026-10-15', lead: 'Dr. Alok Mathur', personnelCount: 6, cargoCount: 3, status: 'Planning', progress: 15, objectives: 'Long-range fixed-wing UAV flights for crevasse field photogrammetry and blue-ice velocity tracking.' },
  { id: 'EXP-2026-08', name: 'Amery Ice Shelf Mass Balance & Crevasse Dynamics', destination: 'Amery Ice Shelf Outpost', station: 'Amery Ice Shelf Outpost', startDate: '2026-06-01', endDate: '2027-02-28', lead: 'Dr. Preeti Joshi', personnelCount: 9, cargoCount: 5, status: 'Planning', progress: 10, objectives: 'Continuous GNSS ice displacement stations and phase-sensitive radar sounding.' },
  { id: 'EXP-2025-09', name: '43rd Indian Scientific Expedition (Wintering Over)', destination: 'Maitri Station', station: 'Maitri Station', startDate: '2024-11-20', endDate: '2025-12-10', lead: 'Dr. Suresh Babu', personnelCount: 24, cargoCount: 16, status: 'Completed', progress: 100, objectives: 'Successful 13-month isolated wintering program, geomagnetic monitoring, and environmental baseline recording.' },
  { id: 'EXP-2025-10', name: 'Weddell Sea Paleoclimate Core Extraction', destination: 'Weddell Sea Sector', station: 'MV Vasiliy Golovnin', startDate: '2025-02-01', endDate: '2025-06-01', lead: 'Dr. K. Ramanathan', personnelCount: 0, cargoCount: 0, status: 'Cancelled', progress: 0, objectives: 'Cancelled due to severe multi-year pack ice obstruction and logistical diversion to Cape Town.' }
];

const cargo = [
  { id: 'CRG-1001', description: 'Aviation Turbine Fuel (Jet A-1 Arctic Grade) - 40 Barrels', category: 'Fuel', origin: 'Cape Town Staging Base', destination: 'Bharati Station', currentLocation: 'Southern Ocean (MV Vasiliy Golovnin)', transportMode: 'Vessel', weight: 8200, priority: 'High', status: 'In Transit', eta: '2026-03-28' },
  { id: 'CRG-1002', description: 'Cummins 250kVA Generator Turbocharger Overhaul Kit', category: 'Spare Parts', origin: 'New Delhi (HQ)', destination: 'Bharati Station', currentLocation: 'Novo Blue Ice Runway', transportMode: 'Aircraft', weight: 450, priority: 'High', status: 'Delayed', eta: '2026-03-24' },
  { id: 'CRG-1003', description: 'Deep Ice Core Drilling Diamond Bits & Drill Rods', category: 'Scientific', origin: 'Goa (NCPOR)', destination: 'Larsemann Hills Camp Beta', currentLocation: 'Bharati Station Cargo Bay', transportMode: 'Ground', weight: 1850, priority: 'Normal', status: 'At Station', eta: '2026-03-20' },
  { id: 'CRG-1004', description: 'Winter High-Calorie Polar Rations & Freeze-Dried Meals', category: 'Food', origin: 'Cape Town Staging Base', destination: 'Maitri Station', currentLocation: 'Maitri Station Storage', transportMode: 'Ground', weight: 3400, priority: 'Normal', status: 'Delivered', eta: '2026-03-15' },
  { id: 'CRG-1005', description: 'Hyperbaric Chamber Replacement Sealants & Valve Assemblies', category: 'Medical', origin: 'Mumbai Naval Yard', destination: 'Bharati Station', currentLocation: 'MV Vasiliy Golovnin', transportMode: 'Vessel', weight: 120, priority: 'High', status: 'In Transit', eta: '2026-03-29' },
  { id: 'CRG-1006', description: 'Extreme-Cold Hydraulic Fluid Polar-Spec (-60°C Rating)', category: 'Fuel', origin: 'Cape Town Staging Base', destination: 'Novo Blue Ice Runway', currentLocation: 'Cape Town Air Cargo Hub', transportMode: 'Aircraft', weight: 1200, priority: 'Normal', status: 'Preparing', eta: '2026-04-02' },
  { id: 'CRG-1007', description: 'Atmospheric Micro-LIDAR Laser Replacement Tube', category: 'Scientific', origin: 'Bengaluru (ISRO)', destination: 'Himadri Research Station', currentLocation: 'Longyearbyen Port Hub', transportMode: 'Ground', weight: 65, priority: 'Normal', status: 'In Transit', eta: '2026-03-26' },
  { id: 'CRG-1008', description: 'PistonBully PB-100 Heavy Duty Caterpillar Track Replacement', category: 'Spare Parts', origin: 'Cape Town Staging Base', destination: 'Maitri Station', currentLocation: 'Novo Blue Ice Runway', transportMode: 'Ground', weight: 1420, priority: 'High', status: 'At Station', eta: '2026-03-22' },
  { id: 'CRG-1009', description: 'Emergency Medical Trauma Kits & Portable Blood Warmer', category: 'Medical', origin: 'New Delhi AIIMS', destination: 'Amery Ice Shelf Outpost', currentLocation: 'Bharati Station Hangar', transportMode: 'Helicopter', weight: 85, priority: 'High', status: 'Delayed', eta: '2026-03-25' },
  { id: 'CRG-1010', description: 'Iridium Certus Polar Maritime Broadband Dome', category: 'Equipment', origin: 'Cape Town Staging Base', destination: 'MV Vasiliy Golovnin', currentLocation: 'MV Vasiliy Golovnin', transportMode: 'Vessel', weight: 95, priority: 'Normal', status: 'Delivered', eta: '2026-03-12' },
  { id: 'CRG-1011', description: 'Sub-surface Moored Acoustic Hydrophone Sensor Cluster', category: 'Scientific', origin: 'Goa (NCPOR)', destination: 'IndARC Observatory', currentLocation: 'Tromso Marine Staging', transportMode: 'Vessel', weight: 310, priority: 'Normal', status: 'Preparing', eta: '2026-04-10' },
  { id: 'CRG-1012', description: 'Ultra-Cold Down Expedition Parkas & Muck Boots (30 sets)', category: 'Personal', origin: 'New Delhi HQ', destination: 'Bharati Station', currentLocation: 'Cape Town Staging Base', transportMode: 'Aircraft', weight: 380, priority: 'Normal', status: 'Loaded', eta: '2026-03-30' },
  { id: 'CRG-1013', description: 'Lithium Iron Phosphate (LiFePO4) Station Energy Storage Bank', category: 'Equipment', origin: 'Chennai Port', destination: 'Maitri Station', currentLocation: 'Southern Ocean (MV Vasiliy Golovnin)', transportMode: 'Vessel', weight: 6800, priority: 'High', status: 'In Transit', eta: '2026-04-05' },
  { id: 'CRG-1014', description: 'Diesel Winter Grade Ultra-Low Sulfur (40 Barrels)', category: 'Fuel', origin: 'Cape Town Staging Base', destination: 'Dakshin Gangotri Ice Depot', currentLocation: 'Cape Town Warehouse', transportMode: 'Vessel', weight: 8600, priority: 'Normal', status: 'Preparing', eta: '2026-04-15' },
  { id: 'CRG-1015', description: 'Multi-Gas Calibration Cylinders & Methane Analyzers', category: 'Scientific', origin: 'National Physical Laboratory', destination: 'Bharati Station', currentLocation: 'Bharati Station Lab', transportMode: 'Ground', weight: 140, priority: 'Normal', status: 'Delivered', eta: '2026-03-18' },
  { id: 'CRG-1016', description: 'Yamaha Snowmobile Steering Rods & Drive Belts', category: 'Spare Parts', origin: 'Cape Town Staging Base', destination: 'Larsemann Hills Camp Beta', currentLocation: 'Bharati Station Hangar', transportMode: 'Ground', weight: 180, priority: 'Normal', status: 'At Station', eta: '2026-03-21' },
  { id: 'CRG-1017', description: 'Medical Oxygen Cylinders (10L Polar-Rated x 12)', category: 'Medical', origin: 'Cape Town Staging Base', destination: 'Bharati Station', currentLocation: 'Novo Blue Ice Runway', transportMode: 'Aircraft', weight: 420, priority: 'High', status: 'In Transit', eta: '2026-03-26' },
  { id: 'CRG-1018', description: 'Fresh Vacuum-Sealed Vegetables & Dairy Provisions', category: 'Food', origin: 'Cape Town Staging Base', destination: 'Maitri Station', currentLocation: 'Novo Blue Ice Runway', transportMode: 'Helicopter', weight: 850, priority: 'High', status: 'In Transit', eta: '2026-03-24' },
  { id: 'CRG-1019', description: 'Raman Spectrometer Precision Optical Laser Diode', category: 'Scientific', origin: 'Goa (NCPOR)', destination: 'Himadri Research Station', currentLocation: 'Ny-Ålesund Receiving Dock', transportMode: 'Ground', weight: 18, priority: 'Normal', status: 'Delivered', eta: '2026-03-16' },
  { id: 'CRG-1020', description: 'Potassium Hydroxide Air Scrubbing Canisters (Life Support)', category: 'Equipment', origin: 'Mumbai Dockyard', destination: 'Bharati Station', currentLocation: 'MV Vasiliy Golovnin', transportMode: 'Vessel', weight: 950, priority: 'High', status: 'In Transit', eta: '2026-03-29' },
  { id: 'CRG-1021', description: 'Autonomous Weather Station (AWS) Mast & Anemometers', category: 'Scientific', origin: 'Pune (IMD)', destination: 'Amery Ice Shelf Outpost', currentLocation: 'Bharati Station Storage', transportMode: 'Helicopter', weight: 260, priority: 'Normal', status: 'Preparing', eta: '2026-04-08' },
  { id: 'CRG-1022', description: 'Glaciology Crevasse Rescue Winches & Dyneema Ropes', category: 'Safety Equipment', origin: 'New Delhi HQ', destination: 'Maitri Station', currentLocation: 'Maitri Station Safety Locker', transportMode: 'Ground', weight: 110, priority: 'High', status: 'Delivered', eta: '2026-03-10' },
  { id: 'CRG-1023', description: 'Emergency Satellite Distress Beacons (COSPAS-SARSAT)', category: 'Safety Equipment', origin: 'Bengaluru (ISRO)', destination: 'Larsemann Hills Camp Beta', currentLocation: 'Bharati Station Comms Bay', transportMode: 'Ground', weight: 45, priority: 'High', status: 'At Station', eta: '2026-03-23' },
  { id: 'CRG-1024', description: 'Reverse Osmosis Desalination High-Pressure Membranes', category: 'Spare Parts', origin: 'Chennai Port', destination: 'Bharati Station', currentLocation: 'MV Vasiliy Golovnin (Damaged Box)', transportMode: 'Vessel', weight: 320, priority: 'Normal', status: 'Damaged', eta: '2026-04-01' },
  { id: 'CRG-1025', description: 'Solar PV Snow-Shedding Panels & MPPT Charge Controllers', category: 'Equipment', origin: 'New Delhi HQ', destination: 'Maitri Station', currentLocation: 'Cape Town Warehouse', transportMode: 'Vessel', weight: 2100, priority: 'Normal', status: 'Preparing', eta: '2026-04-20' },
  { id: 'CRG-1026', description: 'High-Energy Survival Carbohydrate Rations (150 Boxes)', category: 'Food', origin: 'Cape Town Staging Base', destination: 'Dakshin Gangotri Ice Depot', currentLocation: 'Cape Town Staging Base', transportMode: 'Vessel', weight: 1800, priority: 'Normal', status: 'Loaded', eta: '2026-04-12' },
  { id: 'CRG-1027', description: 'Rugged Toughbook Laptops & Field Data Loggers', category: 'Equipment', origin: 'Goa (NCPOR)', destination: 'Himadri Research Station', currentLocation: 'Himadri Base Comms Room', transportMode: 'Aircraft', weight: 75, priority: 'Normal', status: 'Delivered', eta: '2026-03-14' },
  { id: 'CRG-1028', description: 'Aviation Refueling Pump & Filtration Unit', category: 'Equipment', origin: 'Cape Town Staging Base', destination: 'Novo Blue Ice Runway', currentLocation: 'Novo Blue Ice Runway', transportMode: 'Aircraft', weight: 640, priority: 'High', status: 'At Station', eta: '2026-03-22' },
  { id: 'CRG-1029', description: 'Deep Ice Core Insulated Cryo-Storage Transport Crates', category: 'Scientific', origin: 'Goa (NCPOR)', destination: 'Bharati Station', currentLocation: 'Cape Town Air Terminal', transportMode: 'Aircraft', weight: 890, priority: 'Normal', status: 'Preparing', eta: '2026-04-05' },
  { id: 'CRG-1030', description: 'Portable Diesel Space Heaters (Polar-Spec 35kW)', category: 'Equipment', origin: 'Cape Town Staging Base', destination: 'Larsemann Hills Camp Beta', currentLocation: 'Southern Ocean (MV Vasiliy Golovnin)', transportMode: 'Vessel', weight: 520, priority: 'High', status: 'In Transit', eta: '2026-03-29' }
];

const inventory = [
  { id: 'INV-101', item: 'Jet A-1 Arctic Grade Aviation Fuel', category: 'Fuel', station: 'Bharati Station', available: 1200, minimum: 3500, unit: 'Liters', status: 'Critical', lastUpdated: '2026-03-21' },
  { id: 'INV-102', item: 'Station Heating Fuel (Arctic Diesel -50°C)', category: 'Fuel', station: 'Bharati Station', available: 28500, minimum: 15000, unit: 'Liters', status: 'Healthy', lastUpdated: '2026-03-21' },
  { id: 'INV-103', item: 'Medical Oxygen Cylinders (10L 200bar)', category: 'Medical', station: 'Bharati Station', available: 4, minimum: 12, unit: 'Cylinders', status: 'Low Stock', lastUpdated: '2026-03-20' },
  { id: 'INV-104', item: 'Emergency Freeze-Dried Rations (Pack of 50)', category: 'Food', station: 'Bharati Station', available: 140, minimum: 50, unit: 'Packs', status: 'Healthy', lastUpdated: '2026-03-19' },
  { id: 'INV-105', item: 'High-Altitude Hypothermia Thermal Bags', category: 'Medical', station: 'Bharati Station', available: 18, minimum: 15, unit: 'Units', status: 'Healthy', lastUpdated: '2026-03-18' },
  { id: 'INV-106', item: 'Cummins Gen-Set Synthetic Oil (0W-40 Polar)', category: 'Spare Parts', station: 'Bharati Station', available: 180, minimum: 400, unit: 'Liters', status: 'Low Stock', lastUpdated: '2026-03-21' },
  { id: 'INV-107', item: 'Deep Bedrock Diamond Core Drill Bits (HQ)', category: 'Scientific Supplies', station: 'Bharati Station', available: 2, minimum: 8, unit: 'Units', status: 'Critical', lastUpdated: '2026-03-19' },
  { id: 'INV-108', item: 'Snowmobile Drive Belts & Spark Plugs', category: 'Spare Parts', station: 'Bharati Station', available: 32, minimum: 20, unit: 'Sets', status: 'Healthy', lastUpdated: '2026-03-17' },
  { id: 'INV-109', item: 'Water Purification RO Chemical Treatment Kits', category: 'General Supplies', station: 'Bharati Station', available: 8, minimum: 6, unit: 'Kits', status: 'Healthy', lastUpdated: '2026-03-16' },
  { id: 'INV-110', item: 'Potassium Hydroxide CO2 Scrubbing Absorbent', category: 'Safety Equipment', station: 'Bharati Station', available: 650, minimum: 800, unit: 'Kilograms', status: 'Low Stock', lastUpdated: '2026-03-21' },
  
  { id: 'INV-111', item: 'Heating Fuel (Diesel Winter Blend)', category: 'Fuel', station: 'Maitri Station', available: 34000, minimum: 20000, unit: 'Liters', status: 'Healthy', lastUpdated: '2026-03-21' },
  { id: 'INV-112', item: 'Jet A-1 Helicopter Fuel', category: 'Fuel', station: 'Maitri Station', available: 5800, minimum: 4000, unit: 'Liters', status: 'Healthy', lastUpdated: '2026-03-20' },
  { id: 'INV-113', item: 'Broad-Spectrum Antibiotics & Trauma Suture Kits', category: 'Medical', station: 'Maitri Station', available: 22, minimum: 10, unit: 'Kits', status: 'Healthy', lastUpdated: '2026-03-18' },
  { id: 'INV-114', item: 'Flour, Rice & Staples Emergency Reserve', category: 'Food', station: 'Maitri Station', available: 4200, minimum: 2500, unit: 'Kilograms', status: 'Healthy', lastUpdated: '2026-03-15' },
  { id: 'INV-115', item: 'Extreme Cold Survival Polar Tents (4-person)', category: 'Safety Equipment', station: 'Maitri Station', available: 14, minimum: 8, unit: 'Tents', status: 'Healthy', lastUpdated: '2026-03-17' },
  { id: 'INV-116', item: 'PistonBully Track Guide Wheels & Bearings', category: 'Spare Parts', station: 'Maitri Station', available: 3, minimum: 10, unit: 'Units', status: 'Critical', lastUpdated: '2026-03-21' },
  { id: 'INV-117', item: 'Helium Cylinders for Meteorological Weather Balloons', category: 'Scientific Supplies', station: 'Maitri Station', available: 16, minimum: 30, unit: 'Cylinders', status: 'Low Stock', lastUpdated: '2026-03-19' },
  { id: 'INV-118', item: 'VHF Handheld Marine/Polar Radios (GMDSS)', category: 'Safety Equipment', station: 'Maitri Station', available: 28, minimum: 15, unit: 'Radios', status: 'Healthy', lastUpdated: '2026-03-14' },
  { id: 'INV-119', item: 'De-icing Glycol Fluid Type-I', category: 'General Supplies', station: 'Maitri Station', available: 140, minimum: 250, unit: 'Liters', status: 'Low Stock', lastUpdated: '2026-03-20' },
  { id: 'INV-120', item: 'Emergency Rations 24h Individual Pouch', category: 'Food', station: 'Maitri Station', available: 320, minimum: 100, unit: 'Pouches', status: 'Healthy', lastUpdated: '2026-03-16' },

  { id: 'INV-121', item: 'Laboratory Liquid Nitrogen Dewars (50L)', category: 'Scientific Supplies', station: 'Himadri Research Station', available: 2, minimum: 4, unit: 'Dewars', status: 'Low Stock', lastUpdated: '2026-03-20' },
  { id: 'INV-122', item: 'Optical Micro-Filters for Atmospheric Sampling', category: 'Scientific Supplies', station: 'Himadri Research Station', available: 450, minimum: 200, unit: 'Filters', status: 'Healthy', lastUpdated: '2026-03-19' },
  { id: 'INV-123', item: 'Arctic Marine Rations & Tinned Proteins', category: 'Food', station: 'Himadri Research Station', available: 850, minimum: 500, unit: 'Kilograms', status: 'Healthy', lastUpdated: '2026-03-18' },
  { id: 'INV-124', item: 'Emergency Polar Bear Defense Flare Cartridges', category: 'Safety Equipment', station: 'Himadri Research Station', available: 60, minimum: 25, unit: 'Cartridges', status: 'Healthy', lastUpdated: '2026-03-17' },
  { id: 'INV-125', item: 'Snowmobile Heated Visors & Cold Batteries', category: 'Spare Parts', station: 'Himadri Research Station', available: 12, minimum: 8, unit: 'Units', status: 'Healthy', lastUpdated: '2026-03-15' },
  { id: 'INV-126', item: 'IndARC Acoustic Release Lithium Battery Packs', category: 'Spare Parts', station: 'Himadri Research Station', available: 0, minimum: 4, unit: 'Packs', status: 'Out of Stock', lastUpdated: '2026-03-21' },
  { id: 'INV-127', item: 'Ultra-Pure Deionized Water for Lab Analysis', category: 'Scientific Supplies', station: 'Himadri Research Station', available: 80, minimum: 120, unit: 'Liters', status: 'Low Stock', lastUpdated: '2026-03-20' },

  { id: 'INV-128', item: 'Heavy Fuel Oil (Marine Low Sulfur) 500cSt', category: 'Fuel', station: 'MV Vasiliy Golovnin', available: 620000, minimum: 250000, unit: 'Liters', status: 'Healthy', lastUpdated: '2026-03-21' },
  { id: 'INV-129', item: 'Marine Gasoil (MGO) for Auxiliary Generators', category: 'Fuel', station: 'MV Vasiliy Golovnin', available: 95000, minimum: 40000, unit: 'Liters', status: 'Healthy', lastUpdated: '2026-03-21' },
  { id: 'INV-130', item: 'Emergency Survival Immersion Suits (Solas A)', category: 'Safety Equipment', station: 'MV Vasiliy Golovnin', available: 65, minimum: 55, unit: 'Suits', status: 'Healthy', lastUpdated: '2026-03-18' },
  { id: 'INV-131', item: 'Oceanographic Niskin Bottles & Carousel O-Rings', category: 'Scientific Supplies', station: 'MV Vasiliy Golovnin', available: 24, minimum: 18, unit: 'Units', status: 'Healthy', lastUpdated: '2026-03-16' },
  { id: 'INV-132', item: 'Fresh Drinking Water Reserve', category: 'General Supplies', station: 'MV Vasiliy Golovnin', available: 48000, minimum: 20000, unit: 'Liters', status: 'Healthy', lastUpdated: '2026-03-21' },

  { id: 'INV-133', item: 'Jet A-1 Fuel Reserve Drums (Novo Airfield)', category: 'Fuel', station: 'Novo Blue Ice Runway', available: 4200, minimum: 8000, unit: 'Liters', status: 'Critical', lastUpdated: '2026-03-21' },
  { id: 'INV-134', item: 'Runway Surface Friction Testing Calibration Kits', category: 'Equipment', station: 'Novo Blue Ice Runway', available: 2, minimum: 2, unit: 'Kits', status: 'Healthy', lastUpdated: '2026-03-15' },
  { id: 'INV-135', item: 'Sub-Zero Generator Pre-Heater Glow Plugs', category: 'Spare Parts', station: 'Novo Blue Ice Runway', available: 6, minimum: 15, unit: 'Units', status: 'Low Stock', lastUpdated: '2026-03-20' },

  { id: 'INV-136', item: 'Arctic Diesel Sealed Underground Depot Storage', category: 'Fuel', station: 'Dakshin Gangotri Ice Depot', available: 16000, minimum: 10000, unit: 'Liters', status: 'Healthy', lastUpdated: '2026-03-10' },
  { id: 'INV-137', item: 'Emergency Survival Crates (Food & Fuel Dry Mix)', category: 'Food', station: 'Dakshin Gangotri Ice Depot', available: 12, minimum: 10, unit: 'Crates', status: 'Healthy', lastUpdated: '2026-03-10' },

  { id: 'INV-138', item: 'High-Altitude Propane Heating Canisters', category: 'Fuel', station: 'Larsemann Hills Camp Beta', available: 14, minimum: 35, unit: 'Canisters', status: 'Critical', lastUpdated: '2026-03-21' },
  { id: 'INV-139', item: 'Trauma First Aid Field Backpacks', category: 'Medical', station: 'Larsemann Hills Camp Beta', available: 3, minimum: 3, unit: 'Backpacks', status: 'Healthy', lastUpdated: '2026-03-19' },
  { id: 'INV-140', item: 'Deep Glaciological Ice Core Wax Sample Tubes', category: 'Scientific Supplies', station: 'Amery Ice Shelf Outpost', available: 0, minimum: 50, unit: 'Tubes', status: 'Out of Stock', lastUpdated: '2026-03-21' }
];

const assets = [
  { id: 'AST-2001', name: 'Cummins 250kVA Polar Generator #1 (Primary)', category: 'Generators', location: 'Bharati Station', expedition: 'EXP-2026-01', condition: 'Operational', lastMaint: '2026-02-15', nextMaint: '2026-05-15', status: 'Operational', lead: 'Er. Tarun Verma' },
  { id: 'AST-2002', name: 'Cummins 250kVA Polar Generator #2 (Secondary)', category: 'Generators', location: 'Bharati Station', expedition: 'EXP-2026-01', condition: 'Maintenance', lastMaint: '2026-03-18', nextMaint: '2026-03-23', status: 'Maintenance', lead: 'Er. Tarun Verma' },
  { id: 'AST-2003', name: 'Yanmar 60kVA Emergency Gen-Set', category: 'Generators', location: 'Bharati Station', expedition: 'EXP-2026-01', condition: 'Operational', lastMaint: '2026-01-20', nextMaint: '2026-07-20', status: 'Operational', lead: 'Er. Tarun Verma' },
  { id: 'AST-2004', name: 'Kässbohrer PistonBully PB-100 Snow Groomer #1', category: 'Vehicles', location: 'Bharati Station', expedition: 'EXP-2026-01', condition: 'Operational', lastMaint: '2026-02-10', nextMaint: '2026-04-10', status: 'Operational', lead: 'Suresh Negi' },
  { id: 'AST-2005', name: 'Kässbohrer PistonBully PB-100 Snow Groomer #2', category: 'Vehicles', location: 'Bharati Station', expedition: 'EXP-2026-04', condition: 'Maintenance', lastMaint: '2026-03-12', nextMaint: '2026-03-26', status: 'Maintenance', lead: 'Suresh Negi' },
  { id: 'AST-2006', name: 'Yamaha VK540 Heavy Duty Snowmobile (Alpha)', category: 'Vehicles', location: 'Bharati Station', expedition: 'EXP-2026-01', condition: 'Operational', lastMaint: '2026-02-28', nextMaint: '2026-04-30', status: 'Operational', lead: 'Praveen Chhetri' },
  { id: 'AST-2007', name: 'Yamaha VK540 Heavy Duty Snowmobile (Bravo)', category: 'Vehicles', location: 'Bharati Station', expedition: 'EXP-2026-01', condition: 'Damaged', lastMaint: '2026-03-05', nextMaint: '2026-03-28', status: 'Damaged', lead: 'Praveen Chhetri' },
  { id: 'AST-2008', name: 'Ku-Band Earth Tracking Satellite Terminal (4.5m)', category: 'Communication Equipment', location: 'Bharati Station', expedition: 'EXP-2026-01', condition: 'Operational', lastMaint: '2026-02-01', nextMaint: '2026-06-01', status: 'Operational', lead: 'Anita Deshmukh' },
  { id: 'AST-2009', name: 'Atmospheric Micro-Pulse LIDAR System', category: 'Scientific Equipment', location: 'Bharati Station', expedition: 'EXP-2026-01', condition: 'Operational', lastMaint: '2026-01-15', nextMaint: '2026-07-15', status: 'Operational', lead: 'Dr. Sunita Kulkarni' },
  { id: 'AST-2010', name: 'Stationary Hyperbaric Medical Decompression Chamber', category: 'Medical Equipment', location: 'Bharati Station', expedition: 'EXP-2026-01', condition: 'Operational', lastMaint: '2026-02-20', nextMaint: '2026-05-20', status: 'Operational', lead: 'Dr. Sandeep Gill' },

  { id: 'AST-2011', name: 'Caterpillar 180kVA Station Generator (Main)', category: 'Generators', location: 'Maitri Station', expedition: 'EXP-2026-05', condition: 'Operational', lastMaint: '2026-02-14', nextMaint: '2026-05-14', status: 'Operational', lead: 'K. R. Pillai' },
  { id: 'AST-2012', name: 'Caterpillar 180kVA Station Generator (Backup)', category: 'Generators', location: 'Maitri Station', expedition: 'EXP-2026-05', condition: 'Operational', lastMaint: '2026-02-18', nextMaint: '2026-05-18', status: 'Operational', lead: 'K. R. Pillai' },
  { id: 'AST-2013', name: 'Prinoth Bison Arctic Heavy Tractor Cat', category: 'Vehicles', location: 'Maitri Station', expedition: 'EXP-2026-05', condition: 'Operational', lastMaint: '2026-01-25', nextMaint: '2026-04-25', status: 'Operational', lead: 'Sanjay Rawat' },
  { id: 'AST-2014', name: 'Yamaha VK540 Snowmobile Fleet Unit #3', category: 'Vehicles', location: 'Maitri Station', expedition: 'EXP-2026-07', condition: 'Operational', lastMaint: '2026-02-12', nextMaint: '2026-04-12', status: 'Operational', lead: 'Sanjay Rawat' },
  { id: 'AST-2015', name: 'Vaisala DigiCORA Radiosonde Ground Receiver', category: 'Scientific Equipment', location: 'Maitri Station', expedition: 'EXP-2025-09', condition: 'Operational', lastMaint: '2026-02-10', nextMaint: '2026-06-10', status: 'Operational', lead: 'Dr. Alok Mathur' },
  { id: 'AST-2016', name: 'Reverse Osmosis Desalination Unit (1200L/day)', category: 'Safety Equipment', location: 'Maitri Station', expedition: 'EXP-2026-05', condition: 'Operational', lastMaint: '2026-02-05', nextMaint: '2026-05-05', status: 'Operational', lead: 'Er. Tarun Verma' },
  { id: 'AST-2017', name: 'Iridium Extreme Pilot Satellite Comms Array', category: 'Communication Equipment', location: 'Maitri Station', expedition: 'EXP-2026-01', condition: 'Operational', lastMaint: '2026-01-30', nextMaint: '2026-07-30', status: 'Operational', lead: 'Anita Deshmukh' },
  { id: 'AST-2018', name: 'Autonomous Drone SkyRanger R70 Heavy-Lift', category: 'Scientific Equipment', location: 'Maitri Station', expedition: 'EXP-2026-07', condition: 'Operational', lastMaint: '2026-03-01', nextMaint: '2026-06-01', status: 'Operational', lead: 'Dr. Alok Mathur' },

  { id: 'AST-2019', name: 'Microtops II Sunphotometer & Ozonometer', category: 'Scientific Equipment', location: 'Himadri Research Station', expedition: 'EXP-2026-02', condition: 'Operational', lastMaint: '2026-02-11', nextMaint: '2026-08-11', status: 'Operational', lead: 'Dr. Ananya Mukherjee' },
  { id: 'AST-2020', name: 'Confocal Raman Spectrometer Unit', category: 'Scientific Equipment', location: 'Himadri Research Station', expedition: 'EXP-2026-02', condition: 'Operational', lastMaint: '2026-01-18', nextMaint: '2026-07-18', status: 'Operational', lead: 'Dr. Ananya Mukherjee' },
  { id: 'AST-2021', name: 'Ski-Doo Skandic Wide-Track Utility Snowmobile', category: 'Vehicles', location: 'Himadri Research Station', expedition: 'EXP-2026-02', condition: 'Operational', lastMaint: '2026-02-22', nextMaint: '2026-05-22', status: 'Operational', lead: 'Nils Lindqvist' },
  { id: 'AST-2022', name: 'Polar Bear Early Warning Radar & Acoustic Blaster', category: 'Safety Equipment', location: 'Himadri Research Station', expedition: 'EXP-2026-02', condition: 'Operational', lastMaint: '2026-03-02', nextMaint: '2026-06-02', status: 'Operational', lead: 'Nils Lindqvist' },

  { id: 'AST-2023', name: 'IndARC Sub-surface Moored Oceanographic Rig', category: 'Scientific Equipment', location: 'IndARC Observatory', expedition: 'EXP-2026-06', condition: 'Maintenance', lastMaint: '2025-09-15', nextMaint: '2026-04-15', status: 'Maintenance', lead: 'Dr. Meera Nambiar' },
  { id: 'AST-2024', name: 'Sea-Bird SBE 911plus High-Precision CTD Carousel', category: 'Scientific Equipment', location: 'MV Vasiliy Golovnin', expedition: 'EXP-2026-03', condition: 'Operational', lastMaint: '2026-02-25', nextMaint: '2026-05-25', status: 'Operational', lead: 'Dr. Vikramaditya Das' },
  { id: 'AST-2025', name: 'Kongsberg EM 122 Multibeam Deepwater Echo Sounder', category: 'Scientific Equipment', location: 'MV Vasiliy Golovnin', expedition: 'EXP-2026-03', condition: 'Operational', lastMaint: '2026-01-10', nextMaint: '2026-06-10', status: 'Operational', lead: 'Dr. Vikramaditya Das' },
  { id: 'AST-2026', name: 'Bell 412 Twin-Engine Polar Helicopter (Chartered)', category: 'Vehicles', location: 'Novo Blue Ice Runway', expedition: 'EXP-2026-01', condition: 'Operational', lastMaint: '2026-03-08', nextMaint: '2026-04-08', status: 'Operational', lead: 'Capt. A. Zaytsev' },
  { id: 'AST-2027', name: 'Deep Ice Core Electro-Mechanical Drill System', category: 'Scientific Equipment', location: 'Larsemann Hills Camp Beta', expedition: 'EXP-2026-04', condition: 'Operational', lastMaint: '2026-02-26', nextMaint: '2026-05-26', status: 'Operational', lead: 'Dr. Sunita Kulkarni' },
  { id: 'AST-2028', name: 'Amery Glaciological Phase-Sensitive Radar (pRES)', category: 'Scientific Equipment', location: 'Amery Ice Shelf Outpost', expedition: 'EXP-2026-08', condition: 'Operational', lastMaint: '2026-01-12', nextMaint: '2026-07-12', status: 'Operational', lead: 'Dr. Preeti Joshi' },
  { id: 'AST-2029', name: 'PistonBully PB-300 Heavy Snow Tractor (Historical)', category: 'Vehicles', location: 'Dakshin Gangotri Ice Depot', expedition: 'EXP-2025-09', condition: 'Retired', lastMaint: '2024-03-01', nextMaint: 'None', status: 'Retired', lead: 'NCPOR Inventory' },
  { id: 'AST-2030', name: 'Emergency Diesel Space Heater Unit #4', category: 'Generators', location: 'Larsemann Hills Camp Beta', expedition: 'EXP-2026-04', condition: 'Operational', lastMaint: '2026-03-01', nextMaint: '2026-06-01', status: 'Operational', lead: 'Praveen Chhetri' }
];

const personnel = [
  { id: 'PER-501', name: 'Dr. Rajeshwar Sharma', role: 'Expedition Leader', department: 'Polar Science & Operations', expedition: 'EXP-2026-01', location: 'Bharati Station', status: 'At Station', contact: 'sat-phone: +8816-314-2201', clearance: 'Cleared', bloodGroup: 'O+', certs: 'Polar Survival Master, BLS, Leadership' },
  { id: 'PER-502', name: 'Dr. Sandeep Gill', role: 'Chief Medical Officer', department: 'Polar Medicine', expedition: 'EXP-2026-01', location: 'Bharati Station', status: 'At Station', contact: 'sat-phone: +8816-314-2202', clearance: 'Cleared', bloodGroup: 'A+', certs: 'Emergency Trauma Surgery, Hyperbaric Cert' },
  { id: 'PER-503', name: 'Er. Tarun Verma', role: 'Chief Station Engineer', department: 'Engineering & Infrastructure', expedition: 'EXP-2026-01', location: 'Bharati Station', status: 'At Station', contact: 'sat-phone: +8816-314-2203', clearance: 'Cleared', bloodGroup: 'B+', certs: 'Diesel Gen-Set Overhaul, HVAC Polar' },
  { id: 'PER-504', name: 'Dr. Sunita Kulkarni', role: 'Senior Glaciologist', department: 'Glaciology & Cryosphere', expedition: 'EXP-2026-04', location: 'Bharati Station', status: 'At Station', contact: 'sat-phone: +8816-314-2204', clearance: 'Cleared', bloodGroup: 'AB+', certs: 'Crevasse Rescue, Deep Core Drilling' },
  { id: 'PER-505', name: 'Suresh Negi', role: 'Heavy Vehicle Technician', department: 'Logistics & Mechanical', expedition: 'EXP-2026-01', location: 'Bharati Station', status: 'At Station', contact: 'sat-phone: +8816-314-2205', clearance: 'Cleared', bloodGroup: 'O+', certs: 'PistonBully Master Tech, Hydraulic Cert' },
  { id: 'PER-506', name: 'Praveen Chhetri', role: 'Field Operations Specialist', department: 'Safety & Field Logistics', expedition: 'EXP-2026-04', location: 'Larsemann Hills Camp Beta', status: 'Field Deployment', contact: 'vhf: Ch-16 CampBeta', clearance: 'Cleared', bloodGroup: 'A-', certs: 'High Altitude Mountaineering, Crevasse Lead' },
  { id: 'PER-507', name: 'Anita Deshmukh', role: 'Comms & IT Systems Officer', department: 'Information Technology', expedition: 'EXP-2026-01', location: 'Bharati Station', status: 'At Station', contact: 'sat-phone: +8816-314-2207', clearance: 'Cleared', bloodGroup: 'B-', certs: 'Satellite Earth Station Engineer, Cisco CCNA' },
  { id: 'PER-508', name: 'Mohit Bisht', role: 'Atmospheric Scientist', department: 'Atmospheric Physics', expedition: 'EXP-2026-01', location: 'Bharati Station', status: 'At Station', contact: 'int: ext-108', clearance: 'Cleared', bloodGroup: 'O+', certs: 'LIDAR Optical Safety, IMD Met Cert' },
  { id: 'PER-509', name: 'Dinesh Karthik', role: 'Station Chef & Food Logistics', department: 'Catering & Hospitality', expedition: 'EXP-2026-01', location: 'Bharati Station', status: 'At Station', contact: 'int: ext-109', clearance: 'Cleared', bloodGroup: 'O+', certs: 'Extreme Cold Food Preservation, Hygiene Level 4' },
  { id: 'PER-510', name: 'Rohan Deshpande', role: 'Environmental Officer', department: 'Environmental Management', expedition: 'EXP-2026-01', location: 'Bharati Station', status: 'At Station', contact: 'int: ext-110', clearance: 'Cleared', bloodGroup: 'A+', certs: 'Antarctic Protocol Protocol Compliance' },

  { id: 'PER-511', name: 'Dr. Suresh Babu', role: 'Maitri Station Leader', department: 'Polar Science & Operations', expedition: 'EXP-2025-09', location: 'Maitri Station', status: 'At Station', contact: 'sat-phone: +8816-314-3101', clearance: 'Cleared', bloodGroup: 'B+', certs: 'Wintering Over Medalist, Arctic/Antarctic Lead' },
  { id: 'PER-512', name: 'Dr. Pooja Namboodiri', role: 'Station Medical Doctor', department: 'Polar Medicine', expedition: 'EXP-2026-05', location: 'Maitri Station', status: 'At Station', contact: 'sat-phone: +8816-314-3102', clearance: 'Cleared', bloodGroup: 'O-', certs: 'Cold Injury Specialist, BLS/ACLS' },
  { id: 'PER-513', name: 'K. R. Pillai', role: 'Power Plant Specialist', department: 'Engineering & Infrastructure', expedition: 'EXP-2026-05', location: 'Maitri Station', status: 'At Station', contact: 'sat-phone: +8816-314-3103', clearance: 'Cleared', bloodGroup: 'A+', certs: 'Caterpillar Marine Diesel Cert' },
  { id: 'PER-514', name: 'Sanjay Rawat', role: 'Vehicle & Snowmobile Mechanic', department: 'Logistics & Mechanical', expedition: 'EXP-2026-05', location: 'Maitri Station', status: 'At Station', contact: 'int: ext-204', clearance: 'Cleared', bloodGroup: 'B+', certs: 'Snowcat Overhaul, Welding Special 6G' },
  { id: 'PER-515', name: 'Dr. Alok Mathur', role: 'Geophysicist & UAV Lead', department: 'Geophysics', expedition: 'EXP-2026-07', location: 'Maitri Station', status: 'At Station', contact: 'int: ext-205', clearance: 'Cleared', bloodGroup: 'AB-', certs: 'DGCA Certified Drone Pilot, Geomagnetism' },
  { id: 'PER-516', name: 'Rameshwar Tudu', role: 'Life Support Systems Engineer', department: 'Engineering & Infrastructure', expedition: 'EXP-2026-05', location: 'Maitri Station', status: 'At Station', contact: 'int: ext-206', clearance: 'Cleared', bloodGroup: 'O+', certs: 'Water Treatment Polar, Heating Control' },
  { id: 'PER-517', name: 'Vikrant Joshi', role: 'Radio & Navigation Officer', department: 'Information Technology', expedition: 'EXP-2026-05', location: 'Maitri Station', status: 'At Station', contact: 'int: ext-207', clearance: 'Cleared', bloodGroup: 'A+', certs: 'GMDSS General Operator, VHF/HF Specialist' },
  { id: 'PER-518', name: 'Gopal Krishna', role: 'Field Assistant & Guide', department: 'Safety & Field Logistics', expedition: 'EXP-2026-07', location: 'Dakshin Gangotri Ice Depot', status: 'Field Deployment', contact: 'vhf: Ch-16 DGDepot', clearance: 'Cleared', bloodGroup: 'B+', certs: 'Ice Traverse Specialist, Advanced First Aid' },

  { id: 'PER-519', name: 'Dr. Ananya Mukherjee', role: 'Arctic Base Station Leader', department: 'Atmospheric Physics', expedition: 'EXP-2026-02', location: 'Himadri Research Station', status: 'At Station', contact: 'email: ananya@himadri.res.in', clearance: 'Cleared', bloodGroup: 'O+', certs: 'Arctic Expedition Lead, Laser Safety' },
  { id: 'PER-520', name: 'Nils Lindqvist', role: 'Arctic Safety & Polar Bear Guard', department: 'Safety & Field Logistics', expedition: 'EXP-2026-02', location: 'Himadri Research Station', status: 'At Station', contact: 'radio: NyAlesund-11', clearance: 'Cleared', bloodGroup: 'A+', certs: 'Kings Bay Safety Cert, Firearms Polar' },
  { id: 'PER-521', name: 'Dr. Meera Nambiar', role: 'Marine Biologist', department: 'Oceanography', expedition: 'EXP-2026-06', location: 'Himadri Research Station', status: 'At Station', contact: 'email: meera@himadri.res.in', clearance: 'Cleared', bloodGroup: 'B+', certs: 'Scientific Diving AAUS, Plankton Taxonomy' },
  { id: 'PER-522', name: 'Arunav Sengupta', role: 'Microbiologist', department: 'Biological Sciences', expedition: 'EXP-2026-02', location: 'Himadri Research Station', status: 'At Station', contact: 'email: arunav@himadri.res.in', clearance: 'Cleared', bloodGroup: 'O+', certs: 'Cleanroom Protocols, Cryobiology' },

  { id: 'PER-523', name: 'Dr. Vikramaditya Das', role: 'Chief Scientist (Voyage)', department: 'Oceanography', expedition: 'EXP-2026-03', location: 'MV Vasiliy Golovnin', status: 'In Transit', contact: 'inmarsat: +870-773-9021', clearance: 'Cleared', bloodGroup: 'O+', certs: 'Marine Science Lead, STCW-95' },
  { id: 'PER-524', name: 'Capt. A. Zaytsev', role: 'Vessel Ice Master & Pilot', department: 'Maritime Operations', expedition: 'EXP-2026-03', location: 'MV Vasiliy Golovnin', status: 'In Transit', contact: 'inmarsat: Bridge-01', clearance: 'Cleared', bloodGroup: 'A+', certs: 'Polar Ship Master Class 1 Ice' },
  { id: 'PER-525', name: 'Shreya Sundaram', role: 'Marine Chemist', department: 'Chemical Oceanography', expedition: 'EXP-2026-03', location: 'MV Vasiliy Golovnin', status: 'In Transit', contact: 'inmarsat: Lab-02', clearance: 'Cleared', bloodGroup: 'AB+', certs: 'CTD Operation, Nutrients Autoanalyzer' },
  { id: 'PER-526', name: 'Tsering Angchok', role: 'Field Traverse Specialist', department: 'Safety & Field Logistics', expedition: 'EXP-2026-04', location: 'Larsemann Hills Camp Beta', status: 'Field Deployment', contact: 'vhf: Ch-16 CampBeta', clearance: 'Cleared', bloodGroup: 'O+', certs: 'Glacier Crevasse Probe, Cold Wilderness First Aid' },
  { id: 'PER-527', name: 'Dr. Preeti Joshi', role: 'Cryosphere Remote Sensing Lead', department: 'Glaciology & Cryosphere', expedition: 'EXP-2026-08', location: 'Amery Ice Shelf Outpost', status: 'Field Deployment', contact: 'iridium: +8816-992-1044', clearance: 'Cleared', bloodGroup: 'B-', certs: 'Remote Camp Survival, Radar Calibration' },
  { id: 'PER-528', name: 'Gurpreet Singh', role: 'Logistics Officer (Staging)', department: 'Logistics & Supply', expedition: 'EXP-2026-01', location: 'Cape Town Staging Base', status: 'At Station', contact: 'tel: +27-21-449-8011', clearance: 'Cleared', bloodGroup: 'A+', certs: 'IATA Dangerous Goods, Polar Freight Lead' },
  { id: 'PER-529', name: 'Devendra Rana', role: 'Runway Maintenance Chief', department: 'Aviation Logistics', expedition: 'EXP-2026-01', location: 'Novo Blue Ice Runway', status: 'At Station', contact: 'sat: +8816-Novo-99', clearance: 'Cleared', bloodGroup: 'O+', certs: 'Blue Ice Runway Friction, ICAO Polar Ops' },
  { id: 'PER-530', name: 'Kavita Iyer', role: 'Medical Nurse & Paramedic', department: 'Polar Medicine', expedition: 'EXP-2026-04', location: 'Bharati Station', status: 'At Station', contact: 'int: ext-112', clearance: 'Cleared', bloodGroup: 'O-', certs: 'Advanced Cardiac Life Support, Triage Lead' },

  { id: 'PER-531', name: 'Aditya Bhattacharya', role: 'Atmospheric Physics Fellow', department: 'Atmospheric Physics', expedition: 'EXP-2026-01', location: 'Bharati Station', status: 'At Station', contact: 'int: ext-114', clearance: 'Cleared', bloodGroup: 'B+', certs: 'Basic Polar Survival' },
  { id: 'PER-532', name: 'Raghavan Pillai', role: 'Station Electrician', department: 'Engineering & Infrastructure', expedition: 'EXP-2026-01', location: 'Bharati Station', status: 'At Station', contact: 'int: ext-115', clearance: 'Cleared', bloodGroup: 'A+', certs: 'High Voltage Industrial 11kV' },
  { id: 'PER-533', name: 'Hemant Bisht', role: 'Diesel Mechanic Assistant', department: 'Logistics & Mechanical', expedition: 'EXP-2026-05', location: 'Maitri Station', status: 'At Station', contact: 'int: ext-211', clearance: 'Cleared', bloodGroup: 'O+', certs: 'Engine Diagnostics Level 2' },
  { id: 'PER-534', name: 'Sunil Chettiar', role: 'Carpenter & Building Maintenance', department: 'Engineering & Infrastructure', expedition: 'EXP-2026-05', location: 'Maitri Station', status: 'At Station', contact: 'int: ext-212', clearance: 'Cleared', bloodGroup: 'A+', certs: 'Modular Station Assembly' },
  { id: 'PER-535', name: 'Dr. Joyjit Banerjee', role: 'Oceanographer (Postdoc)', department: 'Oceanography', expedition: 'EXP-2026-03', location: 'MV Vasiliy Golovnin', status: 'In Transit', contact: 'inmarsat: Lab-03', clearance: 'Cleared', bloodGroup: 'B+', certs: 'Sea Survival STCW' },
  { id: 'PER-536', name: 'Harpreet Kaur', role: 'Satellite Communications Analyst', department: 'Information Technology', expedition: 'EXP-2026-01', location: 'Bharati Station', status: 'At Station', contact: 'int: ext-116', clearance: 'Cleared', bloodGroup: 'O+', certs: 'RF Link Budget, Antenna Tracking' },
  { id: 'PER-537', name: 'Balwant Chauhan', role: 'Snowcat Driver / Heavy Plant', department: 'Safety & Field Logistics', expedition: 'EXP-2026-04', location: 'Larsemann Hills Camp Beta', status: 'Field Deployment', contact: 'vhf: Ch-16 CampBeta', clearance: 'Cleared', bloodGroup: 'B+', certs: 'Crevasse Detection Radar Ops' },
  { id: 'PER-538', name: 'Deepak Varghese', role: 'Hydrographer', department: 'Oceanography', expedition: 'EXP-2026-06', location: 'Himadri Research Station', status: 'At Station', contact: 'email: deepak@himadri.res.in', clearance: 'Cleared', bloodGroup: 'A+', certs: 'Acoustic Doppler Current Profiling' },
  { id: 'PER-539', name: 'Lt. Col. R. K. Nair', role: 'Defence Liaison & Safety Evaluator', department: 'Safety & Field Logistics', expedition: 'EXP-2026-01', location: 'New Delhi HQ', status: 'Leave', contact: 'hq-tel: +91-11-2460-0199', clearance: 'Cleared', bloodGroup: 'AB+', certs: 'Military Arctic Command' },
  { id: 'PER-540', name: 'Dr. Vinay Saxena', role: 'Physician (Field Quarantined)', department: 'Polar Medicine', expedition: 'EXP-2026-08', location: 'Amery Ice Shelf Outpost', status: 'Medical / Unavailable', contact: 'sat: +8816-992-1045', clearance: 'Restricted', bloodGroup: 'O+', certs: 'Acute Mountain Sickness Observation' }
];

const emergencies = [
  { id: 'INC-201', type: 'Equipment Failure', location: 'Bharati Station', severity: 'Critical', reportedTime: '2026-03-21 06:45 UTC', affectedPersonnel: 'Station Operations (35 on-site)', team: 'Engineering Emergency Quick-Reaction Team', status: 'Response Active', description: 'Primary 250kVA Generator #2 developed catastrophic oil pressure loss and crankshaft bearing overheat. Auxiliary Yanmar gen-set engaged on emergency circuit. Station indoor ambient temperature dropped to 14°C.', logs: ['06:45 — Acoustic and SCADA alarm triggered in Generator Bay', '06:48 — Emergency SCADA switched auxiliary circuit to Yanmar 60kVA', '07:15 — Er. Tarun Verma and Suresh Negi initiated teardown and spare turbo-kit inspection', '08:00 — Heating loops restricted to residential module and medical bay'] },
  { id: 'INC-202', type: 'Weather', location: 'Maitri Station', severity: 'High', reportedTime: '2026-03-21 08:30 UTC', affectedPersonnel: 'Outpost Survey Party (4 personnel)', team: 'Maitri Search & Rescue Traverse Squad', status: 'Acknowledged', description: 'Severe Category-5 Polar Blizzard forecast with sustained winds exceeding 75 knots, gusts over 95 knots, and zero visibility (Whiteout conditions) within 4 hours. Field movements halted.', logs: ['08:30 — IMD Meteorological satellite advisory received', '08:42 — Station Leader Dr. Suresh Babu ordered immediate recall of survey teams', '09:00 — Safety ropes rigged between living container modules'] },
  { id: 'INC-203', type: 'Medical', location: 'Larsemann Hills Camp Beta', severity: 'High', reportedTime: '2026-03-20 22:15 UTC', affectedPersonnel: 'Praveen Chhetri (Field Specialist)', team: 'Bharati Medical Medevac Wing', status: 'Response Active', description: 'Field specialist exhibiting severe Stage-2 hypothermia symptoms, core temp 33.2°C and frostbite on distal phalanges of left foot following unexpected crevasse entrapment during ice core extraction.', logs: ['22:15 — Distress call on VHF Channel 16 received at Bharati Station', '22:30 — Dr. Sandeep Gill briefed Camp Beta via satellite link to administer rewarming protocol', '23:45 — Bell 412 Medevac helicopter put on standby pending wind window'] },
  { id: 'INC-204', type: 'Transportation', location: 'Novo Blue Ice Runway', severity: 'Medium', reportedTime: '2026-03-20 14:10 UTC', affectedPersonnel: 'Logistics Flight Crew (6 personnel)', team: 'Novo Airfield Crash Rescue Unit', status: 'Reported', description: 'IL-76 Transport aircraft cargo hydraulic actuator valve malfunction during taxiing on blue-ice surface. Aircraft safely stationary but obstructing secondary runway apron.', logs: ['14:10 — Air traffic control reported loss of taxi steering control', '14:25 — Emergency tractors dispatched to secure wheels and apply heating blowers'] },
  { id: 'INC-205', type: 'Communication', location: 'Himadri Research Station', severity: 'Medium', reportedTime: '2026-03-19 18:00 UTC', affectedPersonnel: 'Scientific Data Transfer', team: 'Kings Bay Telemetry Taskforce', status: 'Response Active', description: 'Severe ionospheric geomagnetic storm caused complete Ku-band satellite tracking loss and 6-hour communication blackout. Switched telemetry backup to low-speed Iridium burst.', logs: ['18:00 — Ku-band signal-to-noise ratio dropped below decodable threshold', '18:15 — Antenna automated tracking motor re-homed', '20:30 — Partial data sync restored over emergency Iridium SBD modem'] },
  { id: 'INC-206', type: 'Equipment Failure', location: 'Bharati Station', severity: 'Medium', reportedTime: '2026-03-18 11:20 UTC', affectedPersonnel: 'Fuel Storage Farm #3', team: 'Station Hazmat & Fuel Techs', status: 'Resolved', description: 'Micro-crack detected in primary arctic-diesel transfer manifold due to thermal contraction. Minor spill of 25 liters contained immediately in secondary retention bund.', logs: ['11:20 — Pressure differential sensor detected 0.8 bar drop', '11:35 — Suresh Negi applied low-temp composite seal bandage and closed isolation gate valve', '13:00 — Line hydro-tested to 6 bar; zero leakage observed. Incident closed.'] },
  { id: 'INC-207', type: 'Transportation', location: 'MV Vasiliy Golovnin', severity: 'High', reportedTime: '2026-03-16 04:50 UTC', affectedPersonnel: 'Expedition Vessel', team: 'Maritime Engineering Squad', status: 'Resolved', description: 'Heavy multi-year sea pack ice pressure caused temporary rudder hydraulic relief valve trip while breaking 2.5m thick floes in Southern Ocean. Vessel drifted for 45 minutes.', logs: ['04:50 — Chief Engineer notified bridge of hydraulic relief valve trip', '05:15 — Secondary steering gear pump engaged; manual tiller tested', '05:35 — Ship underway on revised polar route at 4 knots. Resolved.'] },
  { id: 'INC-208', type: 'Personnel', location: 'Amery Ice Shelf Outpost', severity: 'Critical', reportedTime: '2026-03-14 09:10 UTC', affectedPersonnel: 'Glaciology Team Alpha (2 personnel)', team: 'Bharati Long-Range SAR Traverse', status: 'Resolved', description: 'Automated satellite beacon failed to transmit scheduled 09:00 UTC safety ping during whiteout traverse. Suspected battery freeze or antenna fracture.', logs: ['09:10 — Automated monitoring flagged missed ping', '09:40 — High-frequency radio directional antenna pinged outpost', '10:15 — Contact established on secondary Iridium handheld; primary antenna had blown over in 65kt gusts. Both personnel safe. Resolved.'] },
  { id: 'INC-209', type: 'Equipment Failure', location: 'Maitri Station', severity: 'Low', reportedTime: '2026-03-12 16:40 UTC', affectedPersonnel: 'Waste Heat Recovery Loop', team: 'Maitri Utilities Team', status: 'Resolved', description: 'Glycol trace heating circuit on grey-water discharge line tripped on over-current, risking pipe freeze-up.', logs: ['16:40 — Alarm logged in central control panel', '17:05 — Blown 30A ceramic fuse replaced with cold-rated spare. Thermal imaging confirmed 45°C flow restored. Resolved.'] },
  { id: 'INC-210', type: 'Equipment Failure', location: 'Novo Blue Ice Runway', severity: 'Low', reportedTime: '2026-03-10 12:15 UTC', affectedPersonnel: 'Runway Survey Unit', team: 'Novo Mechanical Workshop', status: 'Resolved', description: 'Yamaha snowmobile tie-rod end shattered during runway surface ice-friction testing.', logs: ['12:15 — Vehicle towed back to hangar', '13:30 — Spare tie-rod and ball joint installed. Vehicle back in service. Resolved.'] }
];

const tasks = [
  { id: 'TSK-301', title: 'Complete Gen-Set #2 Crankshaft Teardown', description: 'Inspect bearing journal tolerances and replace damaged valve lifters using CRG-1002 overhaul kit.', assignedTo: 'Er. Tarun Verma', expedition: 'EXP-2026-01', priority: 'Critical', dueDate: '2026-03-24', status: 'In Progress' },
  { id: 'TSK-302', title: 'Emergency Medevac Flight Authorization', description: 'Coordinate with Cape Town flight operations for Bell 412 window once blizzard conditions subside.', assignedTo: 'Dr. Rajeshwar Sharma', expedition: 'EXP-2026-01', priority: 'High', dueDate: '2026-03-22', status: 'Pending' },
  { id: 'TSK-303', title: 'Refill Jet A-1 Day-Tanks from Sea Cargo', description: 'Transfer 1,200 liters of polar aviation fuel from MV Vasiliy Golovnin drums to hangar holding tanks.', assignedTo: 'Suresh Negi', expedition: 'EXP-2026-01', priority: 'Critical', dueDate: '2026-03-25', status: 'Pending' },
  { id: 'TSK-304', title: 'Rig Winter Blizzard Lifelines at Maitri', description: 'Check stainless steel safety guide cables between living module, generator house, and met observatory.', assignedTo: 'Sanjay Rawat', expedition: 'EXP-2026-05', priority: 'High', dueDate: '2026-03-22', status: 'In Progress' },
  { id: 'TSK-305', title: 'Calibrate Atmospheric Micro-Pulse LIDAR', description: 'Perform optical alignment with helium-neon laser diode and log baseline photon counts.', assignedTo: 'Mohit Bisht', expedition: 'EXP-2026-01', priority: 'Normal', dueDate: '2026-03-27', status: 'Pending' },
  { id: 'TSK-306', title: 'Annual Ice Core Sample Freezer Audit', description: 'Verify deep ice core storage temperature remains stabilized at -28°C ± 0.5°C across all 4 cryo-vaults.', assignedTo: 'Dr. Sunita Kulkarni', expedition: 'EXP-2026-04', priority: 'Normal', dueDate: '2026-03-29', status: 'Completed' },
  { id: 'TSK-307', title: 'Re-align Ku-Band Satellite Dish at Himadri', description: 'Adjust azimuth and elevation by 1.8 degrees following wind load deflection.', assignedTo: 'Anita Deshmukh', expedition: 'EXP-2026-02', priority: 'High', dueDate: '2026-03-23', status: 'In Progress' },
  { id: 'TSK-308', title: 'Conduct Fire Suppression System Pressure Test', description: 'Inspect FM-200 clean agent cylinders and optical smoke sensors in battery room.', assignedTo: 'K. R. Pillai', expedition: 'EXP-2026-05', priority: 'High', dueDate: '2026-03-26', status: 'Completed' },
  { id: 'TSK-309', title: 'Package Core Samples for Cape Town Dispatch', description: 'Pack 45 meters of Larsemann Hills sediment core into thermally insulated dry-ice containers.', assignedTo: 'Praveen Chhetri', expedition: 'EXP-2026-04', priority: 'Normal', dueDate: '2026-04-02', status: 'Blocked' },
  { id: 'TSK-310', title: 'Update Station Medical Oxygen Inventory', description: 'Perform ultrasonic wall thickness test and record residual pressure across all emergency O2 bottles.', assignedTo: 'Dr. Sandeep Gill', expedition: 'EXP-2026-01', priority: 'Normal', dueDate: '2026-03-24', status: 'In Progress' },
  { id: 'TSK-311', title: 'Inspect PistonBully Track Tensioners', description: 'Check hydraulic track tension cylinder pressures on PB-100 snow groomer Alpha.', assignedTo: 'Suresh Negi', expedition: 'EXP-2026-01', priority: 'Normal', dueDate: '2026-03-25', status: 'Pending' },
  { id: 'TSK-312', title: 'Deploy CTD Rosette at 64°S Station 14', description: 'Perform deep-water hydrographic cast to 3,500m depth for ocean carbon cycle sampling.', assignedTo: 'Dr. Vikramaditya Das', expedition: 'EXP-2026-03', priority: 'High', dueDate: '2026-03-23', status: 'In Progress' },
  { id: 'TSK-313', title: 'Renew Iridium Certus Airtime Licenses', description: 'Synchronize satellite maritime data subscription with NCPOR headquarters logistics desk.', assignedTo: 'Anita Deshmukh', expedition: 'EXP-2026-01', priority: 'Normal', dueDate: '2026-03-31', status: 'Completed' },
  { id: 'TSK-314', title: 'Conduct Monthly Search & Rescue Drill', description: 'Simulate lost-in-blizzard protocol with thermal imaging drones and GPS homing transponders.', assignedTo: 'Dr. Rajeshwar Sharma', expedition: 'EXP-2026-01', priority: 'High', dueDate: '2026-03-28', status: 'Pending' },
  { id: 'TSK-315', title: 'Novo Airfield Friction Coefficient Survey', description: 'Run decelerometer friction tests on central 2,400m of ice runway after fresh snowfall.', assignedTo: 'Devendra Rana', expedition: 'EXP-2026-01', priority: 'High', dueDate: '2026-03-24', status: 'Pending' },
  { id: 'TSK-316', title: 'Hydro-test Reverse Osmosis High-Pressure Lines', description: 'Test desalination piping at 65 bar pressure to prevent brittle fracture in extreme sub-zero conditions.', assignedTo: 'Er. Tarun Verma', expedition: 'EXP-2026-01', priority: 'Normal', dueDate: '2026-03-30', status: 'Completed' },
  { id: 'TSK-317', title: 'Bi-weekly Water Quality & Microbiology Test', description: 'Analyze melted lake water samples for coliforms and dissolved minerals in accordance with WHO standards.', assignedTo: 'Dr. Sandeep Gill', expedition: 'EXP-2026-01', priority: 'Normal', dueDate: '2026-03-22', status: 'Completed' },
  { id: 'TSK-318', title: 'Check Hazardous Chemical Containment Vault', description: 'Verify acid storage ventilation scrubbers and absorbent spill pads at Bharati chemistry laboratory.', assignedTo: 'Rohan Deshpande', expedition: 'EXP-2026-01', priority: 'Low', dueDate: '2026-04-05', status: 'Pending' },
  { id: 'TSK-319', title: 'Install Solar Radiation Shield on Met Tower', description: 'Mount ventilated radiation shield over platinum resistance temperature sensors at Maitri.', assignedTo: 'Dr. Alok Mathur', expedition: 'EXP-2026-07', priority: 'Normal', dueDate: '2026-03-29', status: 'Pending' },
  { id: 'TSK-320', title: 'Audit Emergency Rations at Dakshin Gangotri', description: 'Confirm sealed fuel containers and freeze-dried food pallet integrity via annual overland traverse.', assignedTo: 'Gopal Krishna', expedition: 'EXP-2026-07', priority: 'Normal', dueDate: '2026-04-12', status: 'Blocked' },
  { id: 'TSK-321', title: 'Calibrate Spectroradiometer for Polar Night', description: 'Record dark-current baseline offsets in Arctic winter atmospheric physics cabin.', assignedTo: 'Dr. Ananya Mukherjee', expedition: 'EXP-2026-02', priority: 'Normal', dueDate: '2026-03-25', status: 'Completed' },
  { id: 'TSK-322', title: 'Test Emergency HF Radio Backup Link to Cape Town', description: 'Perform scheduled voice and ALE (Automatic Link Establishment) test on 8,291 kHz USB frequency.', assignedTo: 'Anita Deshmukh', expedition: 'EXP-2026-01', priority: 'High', dueDate: '2026-03-23', status: 'Completed' },
  { id: 'TSK-323', title: 'Inspect Marine Winch Cable on MV Vasiliy Golovnin', description: 'Electromagnetic non-destructive testing of 6,000m oceanographic hydrowire for broken strands.', assignedTo: 'Capt. A. Zaytsev', expedition: 'EXP-2026-03', priority: 'High', dueDate: '2026-03-26', status: 'In Progress' },
  { id: 'TSK-324', title: 'Update Hazardous Material Manifests (IMDG Code)', description: 'Submit digital dangerous goods declarations to Cape Town maritime port authority.', assignedTo: 'Gurpreet Singh', expedition: 'EXP-2026-01', priority: 'Normal', dueDate: '2026-03-27', status: 'In Progress' },
  { id: 'TSK-325', title: 'Clean Photovoltaic Arrays of Glaze Ice', description: 'Manually de-ice snow-shedding solar panels on Maitri roof module to maximize auxiliary power.', assignedTo: 'Suresh Negi', expedition: 'EXP-2026-05', priority: 'Low', dueDate: '2026-03-24', status: 'Completed' },
  { id: 'TSK-326', title: 'Replace Hydraulic Seals on Snowcat PB-100 Bravo', description: 'Swap brittle nitrile O-rings with sub-zero fluorosilicone seals on main blade lift cylinder.', assignedTo: 'Suresh Negi', expedition: 'EXP-2026-01', priority: 'Normal', dueDate: '2026-03-28', status: 'Blocked' },
  { id: 'TSK-327', title: 'Compile Weekly Meteorological Summary for WMO', description: 'Transmit Antarctic synoptic weather observations to World Meteorological Organization GTS network.', assignedTo: 'Mohit Bisht', expedition: 'EXP-2026-01', priority: 'Normal', dueDate: '2026-03-22', status: 'Completed' },
  { id: 'TSK-328', title: 'Review Waste Management & Incinerator Ash Logs', description: 'Ensure full adherence to Protocol on Environmental Protection to the Antarctic Treaty (Madrid Protocol).', assignedTo: 'Rohan Deshpande', expedition: 'EXP-2026-01', priority: 'Low', dueDate: '2026-04-01', status: 'Pending' },
  { id: 'TSK-329', title: 'Recharge Autonomous Weather Station Batteries', description: 'Transport fresh lithium cold-rated packs to Amery Ice Shelf beacon via helicopter sortie.', assignedTo: 'Dr. Preeti Joshi', expedition: 'EXP-2026-08', priority: 'High', dueDate: '2026-04-06', status: 'Pending' },
  { id: 'TSK-330', title: 'Verify Hyperbaric Chamber Oxygen Regulators', description: 'Perform pressure-drop calibration and sterile swab of medical oxygen breathing hoods.', assignedTo: 'Dr. Sandeep Gill', expedition: 'EXP-2026-01', priority: 'Normal', dueDate: '2026-03-25', status: 'In Progress' }
];

const notifications = [
  { id: 'NOTIF-01', category: 'Emergency', title: 'INC-201: Critical Generator Overheat', message: 'Primary Gen-Set #2 at Bharati Station has suffered bearing failure. Yanmar 60kVA backup active.', time: '12 mins ago', read: false },
  { id: 'NOTIF-02', category: 'Inventory', title: 'Critical Fuel Level Alert', message: 'Aviation Jet A-1 inventory at Bharati Station has fallen to 1,200 Liters (Minimum threshold: 3,500 L).', time: '35 mins ago', read: false },
  { id: 'NOTIF-03', category: 'Cargo', title: 'Cargo CRG-1002 Delayed', message: 'Cummins turbo overhaul kit delivery delayed at Novo Runway due to severe weather holding flight.', time: '1 hour ago', read: false },
  { id: 'NOTIF-04', category: 'Emergency', title: 'Blizzard Warning: Maitri Sector', message: 'Category-5 polar blizzard forecast with 85kt gusts expected in 4 hours. Field movements restricted.', time: '2 hours ago', read: false },
  { id: 'NOTIF-05', category: 'Personnel', title: 'Medevac Protocol Standby', message: 'Praveen Chhetri at Camp Beta under rewarming protocol for Stage-2 hypothermia.', time: '3 hours ago', read: true },
  { id: 'NOTIF-06', category: 'Inventory', title: 'Medical Oxygen Below Minimum', message: 'Bharati Station medical bay reports 4 oxygen cylinders remaining (Minimum: 12).', time: '4 hours ago', read: true },
  { id: 'NOTIF-07', category: 'Asset', title: 'Snowcat PB-100 Scheduled Maintenance', message: 'Vehicle maintenance overdue by 48 hours. Preventive service inspection required.', time: '5 hours ago', read: true },
  { id: 'NOTIF-08', category: 'Cargo', title: 'Shipment CRG-1004 Delivered', message: 'High-calorie winter rations safely unloaded at Maitri Station main storage vault.', time: '6 hours ago', read: true },
  { id: 'NOTIF-09', category: 'System', title: 'Satellite Synchronization Event', message: 'High-bandwidth telemetry window via Iridium Certus completed. 42 files synchronized.', time: '8 hours ago', read: true },
  { id: 'NOTIF-10', category: 'Emergency', title: 'INC-206 Resolved', message: 'Minor fuel line leak at Tank Farm #3 isolated and hydro-tested successfully by station engineers.', time: '10 hours ago', read: true },
  { id: 'NOTIF-11', category: 'Personnel', title: 'Medical Clearance Verified', message: 'Dr. Suresh Babu submitted annual cold-environment medical clearance recertification.', time: '12 hours ago', read: true },
  { id: 'NOTIF-12', category: 'Cargo', title: 'Vessel Position Update', message: 'MV Vasiliy Golovnin crossed 64°S latitude entering Antarctic pack ice belt.', time: '14 hours ago', read: true },
  { id: 'NOTIF-13', category: 'Inventory', title: 'Out of Stock: Ice Core Tubes', message: 'Amery Ice Shelf outpost has 0 units remaining for cryo-sediment sampling.', time: '16 hours ago', read: true },
  { id: 'NOTIF-14', category: 'Asset', title: 'IndARC Rig Telemetry Alert', message: 'Moored observatory acoustic ping interval adjusted to low-power winter mode.', time: '18 hours ago', read: true },
  { id: 'NOTIF-15', category: 'System', title: 'Automated Backup Verified', message: 'System database snapshotted to local encrypted vault at Bharati Station local server.', time: '20 hours ago', read: true },
  { id: 'NOTIF-16', category: 'Cargo', title: 'Cargo CRG-1024 Damage Flagged', message: 'Desalination membranes crate sustained exterior crush damage during sea transit.', time: '1 day ago', read: true },
  { id: 'NOTIF-17', category: 'Emergency', title: 'INC-207 Resolved', message: 'MV Vasiliy Golovnin rudder hydraulic relief valve reset; ship proceeding under normal power.', time: '1 day ago', read: true },
  { id: 'NOTIF-18', category: 'Personnel', title: 'Field Party Check-in Confirmed', message: 'Larsemann Hills glaciology party checked in via VHF Channel 16. All accounted for.', time: '1 day ago', read: true },
  { id: 'NOTIF-19', category: 'Inventory', title: 'Fuel Inventory Restock Logged', message: 'Maitri Station logged receipt of 6,000L diesel transfer from overland traverse sledges.', time: '2 days ago', read: true },
  { id: 'NOTIF-20', category: 'Asset', title: 'Ka-Band Weather Radar Online', message: 'Atmospheric radar calibration cycle passed with 99.4% beam efficiency.', time: '2 days ago', read: true },
  { id: 'NOTIF-21', category: 'System', title: 'User Role Updated', message: 'Priya Sen promoted to Inventory Manager with full approval rights on stock requisitions.', time: '2 days ago', read: true },
  { id: 'NOTIF-22', category: 'Cargo', title: 'Aviation Fuel Loaded at Cape Town', message: '40 barrels of Jet A-1 Arctic Grade cleared customs inspection at Cape Town Staging Base.', time: '3 days ago', read: true },
  { id: 'NOTIF-23', category: 'Emergency', title: 'INC-208 Resolved', message: 'Amery Outpost directional radio re-erected. Full telemetry re-established.', time: '3 days ago', read: true },
  { id: 'NOTIF-24', category: 'Inventory', title: 'Low Stock: Li-ion Battery Packs', message: 'IndARC acoustic release spare batteries at zero inventory. Expedited reorder flagged.', time: '3 days ago', read: true },
  { id: 'NOTIF-25', category: 'Personnel', title: 'New Personnel Assigned', message: 'Devendra Rana assigned to Novo Runway as Aviation Maintenance Lead.', time: '4 days ago', read: true },
  { id: 'NOTIF-26', category: 'Asset', title: 'Hyperbaric Chamber Recertified', message: 'Naval diving medical inspector approved annual pressure hull certificate for Bharati chamber.', time: '4 days ago', read: true },
  { id: 'NOTIF-27', category: 'Cargo', title: 'Helicopter Cargo Sortie Completed', message: 'Novo to Bharati air cargo link delivered 420kg priority medical parcels.', time: '5 days ago', read: true },
  { id: 'NOTIF-28', category: 'System', title: 'Security Audit Scan Passed', message: 'Encrypted satellite channel communications audited with zero protocol discrepancies.', time: '5 days ago', read: true },
  { id: 'NOTIF-29', category: 'Emergency', title: 'INC-209 Resolved', message: 'Maitri station waste heat glycol loop de-frosted and electrical fuse replaced.', time: '6 days ago', read: true },
  { id: 'NOTIF-30', category: 'System', title: 'PolarSync System Initialized', message: 'Integrated Polar Expedition Logistics & Asset Management System version 2026.1 operational.', time: '1 week ago', read: true }
];

const documents = [
  { id: 'DOC-101', title: '44th ISEA Master Operations Plan (ISEA-44)', category: 'Expedition Plans', station: 'Bharati Station', size: '14.2 MB', date: '2025-10-15', author: 'Dr. Rajeshwar Sharma', status: 'Approved' },
  { id: 'DOC-102', title: 'MV Vasiliy Golovnin Hazardous Cargo Manifest', category: 'Cargo Manifests', station: 'MV Vasiliy Golovnin', size: '4.8 MB', date: '2026-01-08', author: 'Capt. Sandeep Gill', status: 'Verified' },
  { id: 'DOC-103', title: 'Bharati Station Winter Fuel Reserve Audit', category: 'Inventory Reports', station: 'Bharati Station', size: '2.1 MB', date: '2026-03-01', author: 'Priya Sen', status: 'Critical' },
  { id: 'DOC-104', title: 'Madrid Protocol Antarctic Environmental Compliance Report', category: 'Safety Documents', station: 'Maitri Station', size: '8.6 MB', date: '2026-02-12', author: 'Rohan Deshpande', status: 'Compliant' },
  { id: 'DOC-105', title: 'Cummins 250kVA Generator Overhaul Technical Guide', category: 'Maintenance Records', station: 'Bharati Station', size: '18.4 MB', date: '2025-11-20', author: 'Er. Tarun Verma', status: 'Archived' },
  { id: 'DOC-106', title: 'Emergency Crevasse Rescue & Medevac SOP 2026', category: 'Emergency Reports', station: 'Bharati Station', size: '6.3 MB', date: '2026-01-18', author: 'Dr. Sandeep Gill', status: 'Active' },
  { id: 'DOC-107', title: 'Arctic Winter Campaign Ny-Ålesund Scientific Directive', category: 'Expedition Plans', station: 'Himadri Research Station', size: '7.9 MB', date: '2025-09-25', author: 'Dr. Ananya Mukherjee', status: 'Approved' },
  { id: 'DOC-108', title: 'Cape Town Air-Bridge Cargo Transit Manifest (Sortie 04)', category: 'Cargo Manifests', station: 'Cape Town Staging Base', size: '3.4 MB', date: '2026-03-14', author: 'Gurpreet Singh', status: 'In Transit' },
  { id: 'DOC-109', title: 'Station Medical Bay Drug & Controlled Substance Register', category: 'Inventory Reports', station: 'Bharati Station', size: '1.8 MB', date: '2026-03-15', author: 'Dr. Sandeep Gill', status: 'Verified' },
  { id: 'DOC-110', title: 'PistonBully PB-100 Winterization Checklist', category: 'Maintenance Records', station: 'Maitri Station', size: '5.2 MB', date: '2026-02-04', author: 'Suresh Negi', status: 'Completed' },
  { id: 'DOC-111', title: 'Novo Blue Ice Runway Surface Friction Certification', category: 'Safety Documents', station: 'Novo Blue Ice Runway', size: '3.9 MB', date: '2026-02-28', author: 'Devendra Rana', status: 'Certified' },
  { id: 'DOC-112', title: 'Preliminary Incident Report INC-201 (Gen-Set Failure)', category: 'Emergency Reports', station: 'Bharati Station', size: '4.5 MB', date: '2026-03-21', author: 'Er. Tarun Verma', status: 'Under Review' },
  { id: 'DOC-113', title: 'Southern Ocean Marine Microplastic Baseline Protocol', category: 'Expedition Plans', station: 'MV Vasiliy Golovnin', size: '9.1 MB', date: '2025-12-05', author: 'Dr. Vikramaditya Das', status: 'Approved' },
  { id: 'DOC-114', title: 'IndARC Sub-surface Mooring Acoustic Calibration Data', category: 'Maintenance Records', station: 'IndARC Observatory', size: '12.8 MB', date: '2025-10-30', author: 'Dr. Meera Nambiar', status: 'Archived' },
  { id: 'DOC-115', title: 'Quarterly Cryogenic Liquid Nitrogen Consumption Log', category: 'Inventory Reports', station: 'Himadri Research Station', size: '1.4 MB', date: '2026-02-28', author: 'Dr. Ananya Mukherjee', status: 'Verified' },
  { id: 'DOC-116', title: 'Polar Bear Encounter & Safety Procedures Manual', category: 'Safety Documents', station: 'Himadri Research Station', size: '4.7 MB', date: '2025-08-15', author: 'Nils Lindqvist', status: 'Active' },
  { id: 'DOC-117', title: 'Dakshin Gangotri Depot Structural Assessment', category: 'Maintenance Records', station: 'Dakshin Gangotri Ice Depot', size: '7.2 MB', date: '2026-01-22', author: 'Sunil Chettiar', status: 'Archived' },
  { id: 'DOC-118', title: 'Overland Traverse Fuel Consumption Model & Map', category: 'Expedition Plans', station: 'Maitri Station', size: '11.5 MB', date: '2026-01-10', author: 'Suresh Babu', status: 'Approved' },
  { id: 'DOC-119', title: 'Station Life Support & Water Desalination Health Report', category: 'Inventory Reports', station: 'Bharati Station', size: '3.1 MB', date: '2026-03-10', author: 'Er. Tarun Verma', status: 'Verified' },
  { id: 'DOC-120', title: 'Annual Search and Rescue Readiness Audit 2026', category: 'Safety Documents', station: 'Bharati Station', size: '8.0 MB', date: '2026-02-18', author: 'Dr. Rajeshwar Sharma', status: 'Certified' }
];

const auditLogs = [
  { id: 'AUD-801', timestamp: '2026-03-21 09:12:44 UTC', user: 'admin@polarsync.gov', action: 'EMERGENCY_STATUS_UPDATED', module: 'Emergency', record: 'INC-201', details: 'Updated incident status to Response Active, Yanmar backup verified', ip: '10.240.4.12 (Bharati LAN)', status: 'Success' },
  { id: 'AUD-802', timestamp: '2026-03-21 08:35:10 UTC', user: 'admin@polarsync.gov', action: 'INCIDENT_ACKNOWLEDGED', module: 'Emergency', record: 'INC-202', details: 'Acknowledged Cat-5 Blizzard warning for Maitri sector', ip: '10.240.4.12 (Bharati LAN)', status: 'Success' },
  { id: 'AUD-803', timestamp: '2026-03-21 07:44:22 UTC', user: 'priya.sen@polarsync.gov', action: 'INVENTORY_ADJUSTED', module: 'Inventory', record: 'INV-101', details: 'Adjusted Jet A-1 available stock (-300L) for emergency generator testing', ip: '10.240.4.19', status: 'Success' },
  { id: 'AUD-804', timestamp: '2026-03-21 06:46:05 UTC', user: 'system.monitor', action: 'EMERGENCY_CREATED', module: 'Emergency', record: 'INC-201', details: 'SCADA telemetry triggered Critical equipment failure on Cummins #2', ip: '192.168.10.1 (SCADA Gate)', status: 'Success' },
  { id: 'AUD-805', timestamp: '2026-03-21 06:00:18 UTC', user: 'admin@polarsync.gov', action: 'USER_LOGIN', module: 'Auth', record: 'USR-01', details: 'Successful authentication via PolarSync Command Console', ip: '10.240.4.12', status: 'Success' },
  { id: 'AUD-806', timestamp: '2026-03-20 22:20:41 UTC', user: 'sandeep.gill@polarsync.gov', action: 'EMERGENCY_CREATED', module: 'Emergency', record: 'INC-203', details: 'Logged high severity hypothermia case from Camp Beta', ip: '10.240.4.15', status: 'Success' },
  { id: 'AUD-807', timestamp: '2026-03-20 18:15:29 UTC', user: 'sandeep.gill@polarsync.gov', action: 'CARGO_STATUS_UPDATED', module: 'Cargo', record: 'CRG-1002', details: 'Status updated from In Transit to Delayed due to weather holding flight', ip: '10.240.4.15', status: 'Success' },
  { id: 'AUD-808', timestamp: '2026-03-20 14:12:00 UTC', user: 'devendra.rana@polarsync.gov', action: 'EMERGENCY_CREATED', module: 'Emergency', record: 'INC-204', details: 'Reported runway cargo plane hydraulic fault', ip: '172.16.8.4', status: 'Success' },
  { id: 'AUD-809', timestamp: '2026-03-20 11:30:15 UTC', user: 'tarun.verma@polarsync.gov', action: 'ASSET_MAINTENANCE_LOGGED', module: 'Assets', record: 'AST-2002', details: 'Scheduled maintenance logged for Cummins 250kVA Generator #2', ip: '10.240.4.18', status: 'Success' },
  { id: 'AUD-810', timestamp: '2026-03-19 19:10:04 UTC', user: 'ananya.m@polarsync.gov', action: 'EMERGENCY_CREATED', module: 'Emergency', record: 'INC-205', details: 'Logged Ku-band solar storm tracking failure at Himadri', ip: '193.156.12.8', status: 'Success' },
  { id: 'AUD-811', timestamp: '2026-03-19 15:45:12 UTC', user: 'admin@polarsync.gov', action: 'PERSONNEL_ASSIGNED', module: 'Personnel', record: 'PER-529', details: 'Assigned Devendra Rana to Novo Blue Ice Runway station', ip: '10.240.4.12', status: 'Success' },
  { id: 'AUD-812', timestamp: '2026-03-18 13:02:18 UTC', user: 'tarun.verma@polarsync.gov', action: 'EMERGENCY_RESOLVED', module: 'Emergency', record: 'INC-206', details: 'Resolved minor fuel line leak; hydro-tested and pressure verified', ip: '10.240.4.18', status: 'Success' },
  { id: 'AUD-813', timestamp: '2026-03-18 09:20:33 UTC', user: 'priya.sen@polarsync.gov', action: 'INVENTORY_CREATED', module: 'Inventory', record: 'INV-140', details: 'Registered new inventory tracking item for Amery ice core tubes', ip: '10.240.4.19', status: 'Success' },
  { id: 'AUD-814', timestamp: '2026-03-17 16:50:45 UTC', user: 'admin@polarsync.gov', action: 'EXPEDITION_CREATED', module: 'Expeditions', record: 'EXP-2026-08', details: 'Created Amery Ice Shelf Mass Balance expedition profile', ip: '10.240.4.12', status: 'Success' },
  { id: 'AUD-815', timestamp: '2026-03-16 05:40:11 UTC', user: 'vikram.das@polarsync.gov', action: 'EMERGENCY_RESOLVED', module: 'Emergency', record: 'INC-207', details: 'Icebreaker rudder hydraulics stabilized, vessel continuing south', ip: '192.168.100.2 (Ship V-Sat)', status: 'Success' },
  { id: 'AUD-816', timestamp: '2026-03-15 14:22:09 UTC', user: 'gurpreet.s@polarsync.gov', action: 'CARGO_CREATED', module: 'Cargo', record: 'CRG-1025', details: 'Manifested 2,100kg Solar PV panels for Maitri station upgrade', ip: '41.13.88.2', status: 'Success' },
  { id: 'AUD-817', timestamp: '2026-03-14 10:20:00 UTC', user: 'admin@polarsync.gov', action: 'EMERGENCY_RESOLVED', module: 'Emergency', record: 'INC-208', details: 'Comms re-established with Amery Outpost traverse team', ip: '10.240.4.12', status: 'Success' },
  { id: 'AUD-818', timestamp: '2026-03-13 11:15:30 UTC', user: 'tarun.verma@polarsync.gov', action: 'ASSET_CREATED', module: 'Assets', record: 'AST-2030', details: 'Registered Emergency Diesel Space Heater Unit #4 in inventory', ip: '10.240.4.18', status: 'Success' },
  { id: 'AUD-819', timestamp: '2026-03-12 17:10:55 UTC', user: 'suresh.b@polarsync.gov', action: 'EMERGENCY_RESOLVED', module: 'Emergency', record: 'INC-209', details: 'Replaced glycol loop fuse at Maitri station utilities bay', ip: '10.240.3.5', status: 'Success' },
  { id: 'AUD-820', timestamp: '2026-03-10 13:35:12 UTC', user: 'devendra.rana@polarsync.gov', action: 'EMERGENCY_RESOLVED', module: 'Emergency', record: 'INC-210', details: 'Tie-rod linkage replaced on Yamaha snowmobile; returned to active fleet', ip: '172.16.8.4', status: 'Success' }
];

const users = [
  { id: 'USR-01', name: 'Dr. Rajeshwar Sharma', email: 'admin@polarsync.gov', role: 'Super Admin', department: 'National Centre for Polar & Ocean Research', status: 'Active', lastActive: 'Just now' },
  { id: 'USR-02', name: 'Er. Vandana Rao', email: 'vandana.rao@polarsync.gov', role: 'Expedition Manager', department: 'Antarctic Expedition Operations', status: 'Active', lastActive: '18 mins ago' },
  { id: 'USR-03', name: 'Capt. Sandeep Gill', email: 'sandeep.gill@polarsync.gov', role: 'Logistics Officer', department: 'Polar Maritime & Aviation Logistics', status: 'Active', lastActive: '45 mins ago' },
  { id: 'USR-04', name: 'Priya Sen', email: 'priya.sen@polarsync.gov', role: 'Inventory Manager', department: 'Supply Chain & Material Tracking', status: 'Active', lastActive: '1 hour ago' },
  { id: 'USR-05', name: 'Dr. Tarun Verma', email: 'tarun.verma@polarsync.gov', role: 'Station Officer', department: 'Bharati Station Infrastructure', status: 'Active', lastActive: '2 hours ago' },
  { id: 'USR-06', name: 'Major A. K. Singh', email: 'ak.singh@polarsync.gov', role: 'Emergency Coordinator', department: 'Disaster & Extreme Environment SAR', status: 'Active', lastActive: '3 hours ago' },
  { id: 'USR-07', name: 'Dr. Meera Nambiar', email: 'meera.nambiar@polarsync.gov', role: 'Viewer', department: 'Arctic Scientific Advisory Board', status: 'Active', lastActive: '1 day ago' }
];

module.exports = {
  mockData: {
    stations,
    expeditions,
    cargo,
    inventory,
    assets,
    personnel,
    emergencies,
    tasks,
    notifications,
    documents,
    auditLogs,
    users,
    systemSettings: {
      theme: 'light',
      autoSync: true,
      syncInterval: 30,
      isOnline: true,
      timeFormat: 'UTC',
      dataRefreshed: '2026-03-21T09:12:44Z',
      satelliteStatus: 'Optimal (Iridium 4/4 Bars)'
    }
  }
};
